# NOT USED


# Google OAuth2 Credentials
spring.security.oauth2.client.registration.google.client-id=YOUR_CLIENT_ID.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=YOUR_CLIENT_SECRET

# Scopes (Ask for permission to read Drive files)
spring.security.oauth2.client.registration.google.scope=https://www.googleapis.com/auth/drive.readonly,email,profile

# Optional: Change port if 8080 is busy on your Mac
server.port=8080